### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ank1traj** [sharnett/myweather#32]
You need to set OPENWEATHERMAP_KEY in your environment. Please help me out in this.

**Comment by sharnett** [comment]
1. Sign up for an openweathermap API key here:
https://home.openweathermap.org/users/sign_up
2. Set an environment variable called OPENWEATHERMAP_KEY to your api key.
For Ubuntu and bash that looks like this:
https://askubuntu.com/questions/58814/how-do-i-add-environment-variables
